### ISSUE TITLE
const updatedAt = { ...schema.updatedAt, expires };

### ISSUE THREAD

**Issue by SunShineKG** [mjbondra/koa-session-mongoose#13]
C:\Users\Administrator\Desktop\koa-shop\Koa-onlineShop-api\node_modules\_koa-session-mongoose@2.0.2@koa-session-mongoose\lib\index.js:13
    const updatedAt = { ...schema.updatedAt, expires };
                        ^^^

SyntaxError: Unexpected token ...

**Comment by mjbondra** [comment]
Which version of Node.js are you using? Basic support for `const` has existed without flags since at least v4.

**See: https://github.com/mjbondra/koa-session-mongoose#prerequisites**

This store requires [node@>=8.0.0](https://nodejs.org), [koa@>=2.0.0](http://koajs.com) and [koa-session@>=5.0.0](https://github.com/koajs/session).

If you are using older dependencies, consider using [koa-session-mongoose@\^1.0.0](https://gitlab.com/wondermonger/koa-session-mongoose/tree/v1.0.0).

**Comment by mjbondra** [comment]
This looks like an issue with the use of the spread property `...schema.updatedAt` in the object literal. This requires `node@>=8.3.0`, I will update the readme to reflect that.

http://node.green/#ESNEXT-candidate--stage-3--object-rest-spread-properties-object-spread-properties
